# Generated by Django 5.0.2 on 2024-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code_sent_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
