# Generated by Django 5.0.2 on 2024-05-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_code_sent_time_user_two_factor_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="code_sent_time",
        ),
        migrations.RemoveField(
            model_name="user",
            name="two_factor_code",
        ),
    ]
